name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get Repository name
        id: repository-name
        run: |
          REPOSITORY=${{ github.repository }}
          REPOSITORY_NAME=$(echo $REPOSITORY | cut -d'/' -f2)
          echo "::set-env name=REPOSITORY::$REPOSITORY"
          echo "::set-env name=REPOSITORY_NAME::$REPOSITORY_NAME"

      - name: Git pull at Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git -C ${{ env.REPOSITORY_NAME }} pull || git clone git@github.com:${{ env.REPOSITORY }}.git

      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_EXAMPLE: ${{ secrets.EXAMPLE }}
          file_name: .env

      - name: Upload .env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: .env
          target: ${{ env.REPOSITORY_NAME }}

      - name: Launch as Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.REPOSITORY_NAME }}
            docker-compose up --build -d
